name: API Request with Postman & Puppeteer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Run the request script
      run: node request.js
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}  
